
#banks:
#   bankCode: VNPAY
#   privateKey: ghffffffffff
#   ips:
#
#     bankCode: BIDV
#     privateKey: jjjjjjjj
#     ips:
#bankCode: VNPAY
#privateKey: ghffffffffff
#ips:

banks:
  - bankCode: VNPAY
    privateKey: ghffffffffff
    ips:
  - bankCode: BIDV
    privateKey: jjjjjjjj
    ips: